language: r
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
pandoc_version: 1.17.2

branches:
  only:
  - gh-pages
  - /.*/
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  
script:
  - Rscript -e 'servr:::knit_maybe(c(".", "_source", "_posts"), c(".", "_posts", "_posts"), "build.R", "jekyll")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  target_branch: gh-pages