language: r
pandoc_version: 1.17.2
cache: packages

branches:
  only:
  - gh-pages
  - /.*/

script:
  - Rscript knit.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  target_branch: gh-pages